services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      php-fpm:
        condition: service_healthy
    volumes:
      - ../files/storage:/var/www/storage:ro
      - ../files/public:/var/www/public:ro
    expose:
      - 80
    networks:
      - dokploy-network
      - laravel-production
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../files/storage:/var/www/storage
      - ../files/public:/var/www/public
    networks:
      - laravel-production
      - laravel-production

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootsecret}
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../files/mysql:/var/lib/mysql
    networks:
      - laravel-production

networks:
  dokploy-network:
    external: true
  laravel-production:
